### ISSUE TITLE
Grids have the wrong orientation

### ISSUE THREAD

**Issue by gaitat** [maurizzzio/t3#4]
Your helpers grids are wrong. When someone says I want an XY grid it means I want a grid where the Z axis is perpendicular to it. If I ask for an YZ grid the X axis should be perpendicular to it. That is not the case with your grids.

**Comment by maurizzzio** [comment]
thanks right sir, thanks for the feedback, I've been really busy lately but I'll fix this asap

**Comment by mauriciopoppe** [comment]
solved in 0.3.0
